### ISSUE TITLE
动画抖动

### ISSUE THREAD

**Issue by mxmxixixi** [greensock/GSAP#558] opened 2023-11-29 07:25 UTC
https://github.com/greensock/GSAP/assets/44132969/ef382db9-fb3e-4711-af62-490702dbbc75

在视频中2s-3s中间，出现动画抖动，代码如下
var tl = gsap.to(".box", {
  keyframes:{
    "0%":{scale:0.8},
    "100%":{scale:1}
  },
  transition:{
    ease: "none",
    duration: 0.8,
  }
});
tl.repeat(-1);
tl.yoyo(true);

**Comment by jackdoyle** [comment] 2023-11-29 17:21
I don't quite understand your question. If you need help, please provide a minimal demo, like a CodePen, that clearly illustrates the problem. I wonder if the issue is related to CSS conflicts or some other 3rd party library. Once we see it in context, we'll be able to understand better. 

Also, you should NEVER apply a CSS transition to anything that GSAP is controlling, otherwise you'll create conflicts and prevent GSAP from applying the effects properly. I'm curious why you have a "transition" in that tween.

**Comment by mxmxixixi** [comment] 2023-12-04 02:45
https://codepen.io/mxmxixixi/pen/OJdaEYp

**Comment by mxmxixixi** [comment] 2023-12-04 02:45
https://codepen.io/mxmxixixi/pen/OJdaEYp

**Comment by supuwoerc** [comment] 2023-12-22 09:50
The demo you provided on my side did not reproduce the problem in your video, but I think your code seems too complicated, I think simple breathing effect can be achieved without the help of keyframe.

The cause of stalling may be caused by keyframe. There are many possible reasons for keyframe stalling.

I remember seeing a similar breathing effect in a beginner's tutorial, without the help of keyframe.

https://www.creativecodingclub.com/courses/take/FreeGSAP3Express/lessons/32362027-constant-hover-pulse-with-smooth-reset

```javascript
var tl = gsap.to(".box", {
  scale:1.2,
  ease: "none",
  yoyo:true,
  duration: 0.8,
  repeat:-1
});

```

**Comment by jackdoyle** [comment] 2023-12-29 05:15
I believe I found and fixed the issue. Here's a preview of the next release: 
https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better? 

It'd only happen if the playhead landed EXACTLY on top of the yoyo position in a keyframed animation. 

Sorry about any confusion there.

**Closed** 2024-01-18 22:54 UTC
