### ISSUE TITLE
onComplete in version 3.2.3 does not work correctly

### ISSUE THREAD

**Issue by BorisDibrov** [greensock/GSAP#368] opened 2020-03-02 12:08 UTC
Different behavior in versions 3.1.1 and 3.2.3
Example - [https://codepen.io/borisdibrov/pen/dyoRQxr](https://codepen.io/borisdibrov/pen/dyoRQxr)
onComplete is work differently. In version 3.2.3, the function is ignored if you switch to 3.1.1 everything is ok

**Comment by ZachSaucier** [comment] 2020-03-02 12:47
Hey Boris and thanks for the report. 

The difference seems to have been introduced in version 3.2.0. Maybe it's related to the following?

> - FIXED: if there are no active tweens for a while (and thus GSAP goes to "sleep"), unpausing a tween could lead to it triggering a callback at the incorrect time on that very first tick (as if the resuming animation's startTime wasn't adjusted yet). See https://greensock.com/forums/topic/22753-animation-jumping-on-pause-and-resume/

It seems to work some of the time and fail some of the time, which is surprising.

It seems to always work fine if then is called after the `play()`: https://codepen.io/GreenSock/pen/RwPgExr?editors=0010

**Comment by BorisDibrov** [comment] 2020-03-02 13:56
Very strange, here are two examples.
1 - [First](https://codepen.io/borisdibrov/pen/KKpqJZY)
1 - [Second](https://codepen.io/borisdibrov/pen/KKpqJoY)

The difference is in the order of addition. I can’t understand why this is happening?

**Comment by mtfelian** [comment] 2020-03-02 14:42
Guys i am not a JS developer, but i think the problem is in incorrect usage of arrow functions: 

should be like this: 
```
first.play().then(() => second.play()).then(() => third.play());
```
or just use a normal syntax and everything will take it's places: 

```
const thirdPlayFunc = () => { third.play(); }
const secondPlayFunc = () => { second.play().eventCallback('onComplete', thirdPlayFunc); }
first.play().eventCallback('onComplete', secondPlayFunc);
```

In the author's notation, ```first.play().then(() => second.play().then(() => third.play()));```
first will be resolved an inner promise..

**Comment by mtfelian** [comment] 2020-03-02 15:05
Diving deeper, in first case we have a chain of then's and in each call we pass an arrow function which returns Tween object. In second (author's) case we have a Promise returned to the initial call to `.then()` by the inner call of `.then()`. Probably this is a source of such behavior.

**Comment by jackdoyle** [comment] 2020-03-02 18:12
Aha, I found the issue and it was a regression in 3.2.0 that could cause the onReverseComplete to be fired (prematurely) when you resume a paused animation from its very beginning, and onReverseComplete resolves the .then() Promise too. Sorry about that. It should be fixed in the next release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js - better?

**Comment by BorisDibrov** [comment] 2020-03-03 09:02
Yes. everything is ok! Thanks!

**Closed** 2020-03-04 00:07 UTC
