### ISSUE TITLE
Timeline doesn't complete, intermittently

### ISSUE THREAD

**Issue by TalkingGoose** [greensock/GSAP#358] opened 2020-01-27 17:50 UTC
When using timelines in a specific way, the final animation added never gets called.

This only seems to happen intermittently mind, and there doesn't really seem to be any rhyme or reason as to why it stops.

[Example](https://codepen.io/TalkingGoose/pen/WNbWjbM)

I have added a codepen example above, showing the minimal reproducible code I can create.

After *some random amount of time*, this can be the first iteration or the 100th, the final added callback never resolves, meaning it will never loop.

Sometimes this will never happen, and after a refresh it happens first time to give it a couple refreshes if it doesn't seem to happen for you.

**Comment by ZachSaucier** [comment] 2020-01-27 18:02
Hey TalkingGoose. Thanks for posting.

What are you trying to do with the promises? I'm trying to understand your setup and how you're trying to loop things. 

It looks like you're trying to do something like this: https://codepen.io/GreenSock/pen/JjoVJGN?editors=0010

**Comment by TalkingGoose** [comment] 2020-01-27 18:53
Hey @ZachSaucier 

The linked codepen was just an example of how to reproduce the bug, not an idication of use / intented use.

I've just come across this issue during my use of GSAP within a project and this is a simple replication of a much more complex issue in a different code base.

**Comment by ZachSaucier** [comment] 2020-01-27 18:55
Understood, but I'm trying to understand the structure of the reproduction because it should mirror your setup in production. GSAP has the [.then()](https://greensock.com/docs/v3/GSAP/Tween/then()) method for promises as well as the `repeat` property so I'm trying to understand why you're not using those.

**Comment by TalkingGoose** [comment] 2020-01-27 19:16
The particular method for looping is only for reproduction purposes. The actual code would carry on doing other things and not loop at all. There would be times where you'd end up back in the same location and have it freeze and not continue though.

Asking someone to refresh the page "N" times seemed silly to reproduce the bug though, so I just set a new timeline up again so that it endlessly followed that code path until getting stuck.

I have tested with the ".then()" functionality and that is also susceptible to this same bug.

Are you able to reproduce the described bug using your own devices?

I've managed to reproduce it on 2 different phones, and 2 different desktops although only on Chrome.

**Comment by ZachSaucier** [comment] 2020-01-27 19:18
Your demo does stop looping, yes. But it's a weird method to loop, hence my question. We will continue investigating the issue.

**Comment by jackdoyle** [comment] 2020-01-28 08:47
I believe I tracked down the issue. It had to do with floating point number precision, so a number that should be 1.842, for example, actually ends up as 1.842000000000003 thus fails comparison conditional logic and ultimately skips the very last render of a zero-duration tween/callback that's at the very end of a timeline. That should be resolved in the next release which you can preview at: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

Does that work well for you? 

Thanks so much for providing the reduced test case! Super helpful.

**Comment by TalkingGoose** [comment] 2020-01-28 09:30
I have created a [fork with the linked beta](https://codepen.io/TalkingGoose/full/QWwPZQV), and everything seems to be stable after a good while!

I've currently got a device sat on my desk with the page loaded, so I will leave that running for the day. If anything changes I shall update the issue, otherwise this issue seems to have been resolved.

**Comment by TalkingGoose** [comment] 2020-01-28 09:47
Hey @jackdoyle,

Would there be any way of getting an NPM beta for this change? I can then test this internally on the affected project and confirm it is fixed there too.

Thanks!

**Comment by jackdoyle** [comment] 2020-01-29 07:18
Sure, here's a tarball file that you can `npm install`: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-beta.tgz

**Comment by TalkingGoose** [comment] 2020-01-29 13:35
That seems to have done it! Ran through the affected code path a few thousand times, and no more frozen animations!

Thanks for your expediency in resolving this issue; when should I expect this change to be pushed live?

**Comment by jackdoyle** [comment] 2020-01-30 02:27
> when should I expect this change to be pushed live?

I'm not entirely sure yet, sorry. Maybe a couple of weeks? I just don't want to be too release-happy (iterating version numbers every few days), you know? You're welcome to use that file I sent in the mean time.

**Comment by TalkingGoose** [comment] 2020-02-17 08:05
Hi @jackdoyle, sorry to pester you but I'm looking at including the affected product into a production release soon. 

Due to internal policy I can't release with the beta version, so just wanted to check with you to see how likely a full release would be within the coming week? 🙂

**Comment by jackdoyle** [comment] 2020-02-18 02:31
@TalkingGoose yep, the goal is to push it out later this week. Thanks for your patience.

**Comment by jackdoyle** [comment] 2020-02-22 07:24
Should be fixed in the latest release (3.2.0)

**Closed by jackdoyle** 2020-02-22 07:24 UTC
